[package]
name = "MotooriKosuzu-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.15.18"
dotenv = "0.15.0"
regex = "1.12.2"
serenity = "0.12"
snafu = "0.8.9"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
